services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - placeholder-site
      - typoracer-community

  acme-companion:
    image: nginxproxy/acme-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=${DEFAULT_EMAIL}
    volumes:
      - acme:/etc/acme.sh
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy

  personal-page:
    image: mikkkkkkka/personal-page:latest
    restart: always
    environment:
      - VIRTUAL_HOST=${PERSONAL_PAGE__HOST}
      - LETSENCRYPT_HOST=${PERSONAL_PAGE__HOST}
      - LETSENCRYPT_EMAIL=${DEFAULT_EMAIL}

  typoracer-community:
    image: mikkkkkkka/typoracer-community:latest
    restart: always
    environment:
      - VIRTUAL_HOST=${TYPORACER_COMMUNITY__SITE__HOST}
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=${TYPORACER_COMMUNITY__SITE__HOST}
      - LETSENCRYPT_EMAIL=${DEFAULT_EMAIL}
      - DATABASE_URL=${TYPORACER_COMMUNITY__SITE__DATABASE_URL}
      - NODE_ENV=production
    depends_on:
      typoracer-community-db:
        condition: service_healthy

  typoracer-community-db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=${TYPORACER_COMMUNITY__DB__USER}
      - POSTGRES_PASSWORD=${TYPORACER_COMMUNITY__DB__PASSWORD}
      - POSTGRES_DB=${TYPORACER_COMMUNITY__DB__NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\""]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - typoracer-community-db-data:/var/lib/postgresql/data
    ports:
      - "${TYPORACER_COMMUNITY__DB__EXPORT_PORT}:5432"

  what-i-know-api:
    image: mikkkkkkka/what-i-know-api:latest
    restart: always
    environment:
      - VIRTUAL_HOST=${WHAT_I_KNOW__API__HOST}
      - VIRTUAL_PORT=${WHAT_I_KNOW__API__HTTP_ADDRESS}
      - LETSENCRYPT_HOST=${WHAT_I_KNOW__API__HOST}
      - LETSENCRYPT_EMAIL=${DEFAULT_EMAIL}

      - DB_HOST=${WHAT_I_KNOW__DB__HOST}
      - DB_PORT=5432
      - DB_USER=${WHAT_I_KNOW__DB__USER}
      - DB_PASSWORD=${WHAT_I_KNOW__DB__PASSWORD}
      - DB_NAME=${WHAT_I_KNOW__DB__NAME}
      - DB_SSL_MODE=${WHAT_I_KNOW__DB__SSL_MODE}
      - HTTP_ADDRESS=:${WHAT_I_KNOW__API__HTTP_ADDRESS}
      - HTTP_API_BASE_PATH=${WHAT_I_KNOW__API__HTTP_API_BASE_PATH}
      - HTTP_READ_TIMEOUT_SECONDS=${WHAT_I_KNOW__API__HTTP_READ_TIMEOUT_SECONDS}
      - HTTP_WRITE_TIMEOUT_SECONDS=${WHAT_I_KNOW__API__HTTP_WRITE_TIMEOUT_SECONDS}
      - HTTP_IDLE_TIMEOUT_SECONDS=${WHAT_I_KNOW__API__HTTP_IDLE_TIMEOUT_SECONDS}
      - HTTP_SHUTDOWN_TIMEOUT_SECONDS=${WHAT_I_KNOW__API__HTTP_SHUTDOWN_TIMEOUT_SECONDS}
      - JWT_SECRET=${WHAT_I_KNOW__API__JWT_SECRET}
    depends_on:
      what-i-know-db:
        condition: service_healthy
  
  what-i-know-db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=${WHAT_I_KNOW__DB__USER}
      - POSTGRES_PASSWORD=${WHAT_I_KNOW__DB__PASSWORD}
      - POSTGRES_DB=${WHAT_I_KNOW__DB__NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\""]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - what-i-know-db-data:/var/lib/postgresql/data
    ports:
      - "${WHAT_I_KNOW__DB__EXPORT_PORT}:5432"

volumes:
  acme:
  certs:
  vhost:
  html:
  what-i-know-db-data:
  typoracer-community-db-data:
