version: "3.8"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - placeholder-site
      - web-backend

  acme-companion:
    image: nginxproxy/acme-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=${DEFAULT_EMAIL}
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy

  placeholder-site:
    image: mikkkkkkka/placeholder-site:latest
    restart: always
    environment:
      - VIRTUAL_HOST=${PLACEHOLDER_SITE_HOST}
      - LETSENCRYPT_HOST=${PLACEHOLDER_SITE_HOST}
      - LETSENCRYPT_EMAIL=${DEFAULT_EMAIL}

  web-backend:
    image: mikkkkkkka/m3303-kashin-backend:latest
    restart: always
    environment:
      - VIRTUAL_HOST=${WEB_BACKEND_SITE_HOST}
      - LETSENCRYPT_HOST=${WEB_BACKEND_SITE_HOST}
      - LETSENCRYPT_EMAIL=${DEFAULT_EMAIL}

volumes:
  certs:
  vhost:
  html: